# test-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transit-api
  template:
    metadata:
      labels:
        app: transit-api
    spec:
      containers:
      - name: transit-api
        image: sodiqtesttransitregistry.azurecr.io/transitapi:1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: transit-api-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: transit-api
